chuoi = input("Nhập vào một câu: ")
chuoi = chuoi.strip()
print("Chuỗi sau khi loại bỏ khoảng trắng:", chuoi)
chuoi_thuong = chuoi.lower()
print("Chuỗi sau khi chuyển thành chữ thường:", chuoi_thuong)
chuoi_thay = chuoi_thuong.replace("bad", "***")
print("Chuỗi sau khi thay thế từ 'bad':", chuoi_thay)
so_lan = chuoi_thuong.count("the")
print("Số lần xuất hiện của từ 'the':", so_lan)
